### ISSUE TITLE
Running NPM start fails

### ISSUE THREAD

**Issue by awaredigital** [artf/grapesjs-tabs#9]
Im trying to do some dev work on the tabs for grapes and tried to get them installed and working.

I get the following error after:

`npm i && npm start`

```
grapesjs-tabs/node_modules/yargs/yargs.js:1171
      else throw err
           ^


TypeError: Cannot read property 'entry' of undefined
    at module.exports (/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/src/webpack.config.js:27:37)
    at serve (/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/src/main.js:52:12)
    at Object.yargs.command [as handler] (/Sites/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/src/cli.js:25:18)
    at Object.runCommand (/Sites/grapes/grapesjs-tabs/node_modules/yargs/lib/command.js:235:26)
    at Object.parseArgs [as _parseArgs] (/Sites/grapes/grapesjs-tabs/node_modules/yargs/yargs.js:1086:30)
    at Object.get [as argv] /Sites/grapes/grapesjs-tabs/node_modules/yargs/yargs.js:1020:21)
    at argsToOpts (/Sites/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/src/cli.js:76:13)
    at Proxy.default (/Sites/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/src/cli.js:85:19)
    at Object.<anonymous> (/Sites/grapes/grapesjs-tabs/node_modules/grapesjs-dev-helper/bin/grapesjs-dev-helper:4:30)
    at Module._compile (module.js:624:30)
```

What version of node - webpack should i be running currently using: 11.12.0 npm and webpack 4.41.2

**Comment by artf** [comment]
Thanks @awaredigital for the report. This release https://github.com/artf/grapesjs-tabs/releases/tag/v0.2.2 should have fix the issue
